#!/usr/local/bin/expect -f
spawn telnet
send "open quote.yahoo.com 80\r"
expect "Escape character is '^]'.\r"
send "GET /download/quotes.csv?symbols=^dji+^ixic+glm+esv+msft+IBM+inss&format=sl1d1t1c1ohgv&ext=.csv\r"
log_file -a pq.csv
interact

